---
title: "Data Acquisition"
author: "Nandan Rajkumar"
---

::: callout-note
You can delete everything in here and start fresh.
:::
#Load Libraries
```{r}
library(RSQLite)
library(dplyr)
library(httr)
library(glue)
library(jsonlite)
library(keyring)
library("rstudioapi")
library(rvest)

```
#Sending the GET request to the API
```{r}
response <- GET("https://www.themealdb.com/api/json/v1/1/filter.php?c=Seafood")
```
#Checking the status code and print first ten rows of your tibbles
```{r}
if (response$status_code == 200) {
  # The request was successful
  # Get the response data
  rawToChar(response$content)
  
  meals_db <- response %>%
    .$content %>%
    rawToChar() %>%
    fromJSON()
  #-- Print the first 10 rows of your tibbles
  head(meals_db)
} else {
  # The request failed
  print(response$status_code)
}
```
#Scrape one of the competitor websites of canyon and create a small database.
```{r}
# Set the URL of the website to scrape
url <- "https://www.rosebikes.de/"

# Scrape the website
html <- read_html(url)

# Find the elements that contain the model names
model_names <- html %>%
  html_nodes(".products-slider-tile__product-name") %>%
  html_text()

# Find the elements that contain the prices
prices <- html %>%
  html_nodes(".product-tile-price__current-value") %>%
  html_text()

# Extract the number using regular expressions
price <- gsub("[^0-9.,]", "", prices)  # Remove all non-digit, non-decimal, and non-comma characters

# Create a data frame of the model names and prices
database <- data.frame(
  Model = model_names,
  Price = price
)

# Print the data frame
print(database)


```
